const questions = [
  {
    questionId: 1,
    category: "Career Guidance",
    text: "What is your preferred career field?",
    type: "multiple_choice",
    options: ["Technology", "Health", "Finance", "Education", "Arts", "Other"],
    nextRule: { "Technology": 3, Health: 3, Finance: 3, Education: 3, Arts: 3, Other: 3 },
  },
  {
    questionId: 2,
    category: "Career Guidance",
    text: "What is your highest level of education?",
    type: "multiple_choice",
    options: ["High School", "Undergraduate", "Postgraduate", "Other"],
    nextRule: { "High School": 4, "Undergraduate": 4, "Postgraduate": 4, "Other": 4 },
  },
  {
    questionId: 3,
    category: "Career Guidance",
    text: "Which of the following interests you the most?",
    type: "multiple_choice",
    options: ["Technology", "Health", "Finance", "Education", "Arts", "Other"],
    nextRule: { Technology: 5, Health: 5, Finance: 5, Education: 5, Arts: 5, Other: 5 },
  },
  {
    questionId: 4,
    category: "Career Guidance",
    text: "Do you have any prior work experience in your chosen field?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { Yes: 5, No: 6 },
  },
  {
    questionId: 5,
    category: "Career Guidance",
    text: "How many years of experience do you have in your chosen field?",
    type: "multiple_choice",
    options: ["Less than 1 year", "1-3 years", "3-5 years", "5+ years"],
    nextRule: { "Less than 1 year": 7, "1-3 years": 7, "3-5 years": 7, "5+ years": 7 },
  },
  {
    questionId: 6,
    category: "Career Guidance",
    text: "Would you like to pursue additional education or training to advance your career?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { Yes: 7, No: 8 },
  },
  {
    questionId: 7,
    category: "Career Guidance",
    text: "What type of additional education or training would you consider?",
    type: "multiple_choice",
    options: ["Certification", "Degree", "Workshops", "Online Courses", "Other"],
    nextRule: { Certification: 9, Degree: 9, Workshops: 9, "Online Courses": 9, Other: 9 },
  },
  {
    questionId: 8,
    category: "Career Guidance",
    text: "What challenges do you face in your career growth?",
    type: "multiple_choice",
    options: ["Lack of opportunities", "Skill gap", "Lack of mentorship", "Work-life balance", "Other"],
    nextRule: { "Lack of opportunities": 10, "Skill gap": 10, "Lack of mentorship": 10, "Work-life balance": 10, Other: 10 },
  },
  {
    questionId: 9,
    category: "Career Guidance",
    text: "What type of work environment do you thrive in?",
    type: "multiple_choice",
    options: ["Corporate", "Start-up", "Freelance", "Non-profit", "Other"],
    nextRule: { Corporate: 11, "Start-up": 11, Freelance: 11, "Non-profit": 11, Other: 11 },
  },
  {
    questionId: 10,
    category: "Career Guidance",
    text: "Do you prefer working alone or in a team?",
    type: "multiple_choice",
    options: ["Alone", "In a Team"],
    nextRule: { Alone: 12, "In a Team": 12 },
  },
  {
    questionId: 11,
    category: "Career Guidance",
    text: "What motivates you the most in your career?",
    type: "multiple_choice",
    options: ["Recognition", "Growth opportunities", "Work-life balance", "Salary", "Other"],
    nextRule: { Recognition: 13, "Growth opportunities": 13, "Work-life balance": 13, Salary: 13, Other: 13 },
  },
  {
    questionId: 12,
    category: "Career Guidance",
    text: "Would you consider changing industries for better career prospects?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { Yes: 13, No: 14 },
  },
  {
    questionId: 13,
    category: "Career Guidance",
    text: "Which industry would you like to transition to?",
    type: "multiple_choice",
    options: ["Technology", "Health", "Finance", "Education", "Other"],
    nextRule: { Technology: 15, Health: 15, Finance: 15, Education: 15, Other: 15 },
  },
  {
    questionId: 14,
    category: "Career Guidance",
    text: "What skills do you want to develop for your career?",
    type: "multiple_choice",
    options: ["Leadership", "Communication", "Technical Skills", "Problem Solving", "Other"],
    nextRule: { Leadership: 16, Communication: 16, "Technical Skills": 16, "Problem Solving": 16, Other: 16 },
  },
  {
    questionId: 15,
    category: "Career Guidance",
    text: "Would you be interested in mentoring others in your field?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { Yes: 17, No: 18 },
  },
  {
    questionId: 16,
    category: "Career Guidance",
    text: "Would you like to take on more leadership roles in your career?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { Yes: 18, No: 18 },
  },
  {
    questionId: 17,
    category: "Career Guidance",
    text: "What type of leadership roles would you like to pursue?",
    type: "multiple_choice",
    options: ["Team Leader", "Manager", "Director", "Executive", "Other"],
    nextRule: { "Team Leader": 19, Manager: 19, Director: 19, Executive: 19, Other: 19 },
  },
  {
    questionId: 18,
    category: "Career Guidance",
    text: "What are your future career aspirations?",
    type: "multiple_choice",
    options: ["Become an Expert", "Start My Own Business", "Climb the Corporate Ladder", "Other"],
    nextRule: { "Become an Expert": 20, "Start My Own Business": 20, "Climb the Corporate Ladder": 20, Other: 20 },
  },
  {
    questionId: 19,
    category: "Career Guidance",
    text: "What level of responsibility do you prefer in your career?",
    type: "multiple_choice",
    options: ["Low", "Medium", "High"],
    nextRule: { Low: 20, Medium: 20, High: 20 },
  },
  {
    questionId: 20,
    category: "Career Guidance",
    text: "What work-life balance do you seek?",
    type: "multiple_choice",
    options: ["Very Balanced", "Moderate", "Not Important"],
    nextRule: { "Very Balanced": 21, Moderate: 21, "Not Important": 21 },
  },
  {
    questionId: 21,
    category: "Career Guidance",
    text: "How much do you value job stability?",
    type: "multiple_choice",
    options: ["Very Important", "Moderately Important", "Not Important"],
    nextRule: { "Very Important": 22, "Moderately Important": 22, "Not Important": 22 },
  },
  {
    questionId: 22,
    category: "Career Guidance",
    text: "Are you willing to relocate for better career opportunities?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { Yes: 23, No: 24 },
  },
  {
    questionId: 23,
    category: "Career Guidance",
    text: "What regions would you consider relocating to?",
    type: "multiple_choice",
    options: ["North America", "Europe", "Asia", "Other"],
    nextRule: { "North America": 25, Europe: 25, Asia: 25, Other: 25 },
  },
  {
    questionId: 24,
    category: "Career Guidance",
    text: "Are you interested in remote work opportunities?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { Yes: 25, No: 26 },
  },
  {
    questionId: 25,
    category: "Career Guidance",
    text: "What benefits are most important to you in a job?",
    type: "multiple_choice",
    options: ["Health Insurance", "Retirement Plans", "Paid Time Off", "Other"],
    nextRule: { "Health Insurance": 27, "Retirement Plans": 27, "Paid Time Off": 27, Other: 27 },
  },
  {
    questionId: 26,
    category: "Career Guidance",
    text: "What is your ideal company culture?",
    type: "multiple_choice",
    options: ["Collaborative", "Competitive", "Innovative", "Traditional", "Other"],
    nextRule: { Collaborative: 28, Competitive: 28, Innovative: 28, Traditional: 28, Other: 28 },
  },
  {
    questionId: 27,
    category: "Career Guidance",
    text: "How do you prefer to receive feedback at work?",
    type: "multiple_choice",
    options: ["Frequent feedback", "Occasional feedback", "As needed", "No preference"],
    nextRule: { "Frequent feedback": 29, "Occasional feedback": 29, "As needed": 29, "No preference": 29 },
  },
  {
    questionId: 28,
    category: "Career Guidance",
    text: "Do you prefer structured tasks or more flexibility in your work?",
    type: "multiple_choice",
    options: ["Structured tasks", "Flexibility", "A mix of both"],
    nextRule: { "Structured tasks": 30, Flexibility: 30, "A mix of both": 30 },
  },
  {
    questionId: 29,
    category: "Career Guidance",
    text: "How important is work environment for your job satisfaction?",
    type: "multiple_choice",
    options: ["Very important", "Somewhat important", "Not important"],
    nextRule: { "Very important": 30, "Somewhat important": 30, "Not important": 30 },
  },
  {
    questionId: 30,
    category: "Career Guidance",
    text: "Are you satisfied with your current career progression?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { Yes: null, No: null }, // End of the questionnaire
  },
  {
    questionId: 1,
    category: "Parenting",
    text: "How old is your child?",
    type: "multiple_choice",
    options: ["0-1 years", "1-3 years", "4-6 years", "7-9 years", "10+ years"],
    nextRule: { "0-1 years": 3, "1-3 years": 3, "4-6 years": 3, "7-9 years": 3, "10+ years": 3 },
  },
  {
    questionId: 2,
    category: "Parenting",
    text: "What is your parenting style?",
    type: "multiple_choice",
    options: ["Authoritative", "Authoritarian", "Permissive", "Uninvolved"],
    nextRule: { Authoritative: 4, Authoritarian: 4, Permissive: 4, Uninvolved: 4 },
  },
  {
    questionId: 3,
    category: "Parenting",
    text: "What type of schooling is your child enrolled in?",
    type: "multiple_choice",
    options: ["Public School", "Private School", "Homeschooling", "Not yet enrolled"],
    nextRule: { "Public School": 5, "Private School": 5, "Homeschooling": 5, "Not yet enrolled": 5 },
  },
  {
    questionId: 4,
    category: "Parenting",
    text: "Do you provide positive reinforcement to encourage good behavior?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { Yes: 6, No: 7 },
  },
  {
    questionId: 5,
    category: "Parenting",
    text: "How do you handle your child's tantrums?",
    type: "multiple_choice",
    options: ["Ignore them", "Talk to them calmly", "Give them a timeout", "Give in to their demands"],
    nextRule: { "Ignore them": 8, "Talk to them calmly": 8, "Give them a timeout": 8, "Give in to their demands": 8 },
  },
  {
    questionId: 6,
    category: "Parenting",
    text: "Do you have a set bedtime routine for your child?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { Yes: 9, No: 10 },
  },
  {
    questionId: 7,
    category: "Parenting",
    text: "Would you consider seeking professional parenting advice?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { Yes: 11, No: 12 },
  },
  {
    questionId: 8,
    category: "Parenting",
    text: "How do you encourage your child to be independent?",
    type: "multiple_choice",
    options: ["Giving them chores", "Letting them make decisions", "Praise for small achievements", "Other"],
    nextRule: { "Giving them chores": 13, "Letting them make decisions": 13, "Praise for small achievements": 13, Other: 13 },
  },
  {
    questionId: 9,
    category: "Parenting",
    text: "How do you manage your child's screen time?",
    type: "multiple_choice",
    options: ["No screen time", "Set time limits", "No limits, unrestricted", "Other"],
    nextRule: { "No screen time": 14, "Set time limits": 14, "No limits, unrestricted": 14, Other: 14 },
  },
  {
    questionId: 10,
    category: "Parenting",
    text: "How often do you spend quality one-on-one time with your child?",
    type: "multiple_choice",
    options: ["Every day", "Several times a week", "Once a week", "Once a month or less"],
    nextRule: { "Every day": 15, "Several times a week": 15, "Once a week": 15, "Once a month or less": 15 },
  },
  {
    questionId: 11,
    category: "Parenting",
    text: "Do you provide your child with an allowance?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { Yes: 16, No: 17 },
  },
  {
    questionId: 12,
    category: "Parenting",
    text: "How do you handle your child's social interactions with other children?",
    type: "multiple_choice",
    options: ["Arrange playdates", "Allow them to meet other kids at school", "Monitor closely", "Other"],
    nextRule: { "Arrange playdates": 18, "Allow them to meet other kids at school": 18, "Monitor closely": 18, Other: 18 },
  },
  {
    questionId: 13,
    category: "Parenting",
    text: "How do you encourage healthy eating habits in your child?",
    type: "multiple_choice",
    options: ["Providing nutritious meals", "Limiting junk food", "Teaching them about healthy choices", "Other"],
    nextRule: { "Providing nutritious meals": 19, "Limiting junk food": 19, "Teaching them about healthy choices": 19, Other: 19 },
  },
  {
    questionId: 14,
    category: "Parenting",
    text: "Do you monitor your child's online activities?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { Yes: 20, No: 21 },
  },
  {
    questionId: 15,
    category: "Parenting",
    text: "What method do you prefer for disciplining your child?",
    type: "multiple_choice",
    options: ["Time-outs", "Verbal reprimands", "Natural consequences", "Spanking"],
    nextRule: { "Time-outs": 22, "Verbal reprimands": 22, "Natural consequences": 22, Spanking: 22 },
  },
  {
    questionId: 16,
    category: "Parenting",
    text: "How do you handle your child's bad behavior in public?",
    type: "multiple_choice",
    options: ["Ignore it", "Talk to them privately", "Discipline them in public", "Other"],
    nextRule: { "Ignore it": 23, "Talk to them privately": 23, "Discipline them in public": 23, Other: 23 },
  },
  {
    questionId: 17,
    category: "Parenting",
    text: "Do you feel confident in your parenting skills?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { Yes: 24, No: 25 },
  },
  {
    questionId: 18,
    category: "Parenting",
    text: "How do you handle your child's emotional well-being?",
    type: "multiple_choice",
    options: ["Provide emotional support", "Talk about feelings", "Encourage self-expression", "Other"],
    nextRule: { "Provide emotional support": 26, "Talk about feelings": 26, "Encourage self-expression": 26, Other: 26 },
  },
  {
    questionId: 19,
    category: "Parenting",
    text: "How often do you discuss important life values with your child?",
    type: "multiple_choice",
    options: ["Daily", "Weekly", "Monthly", "Rarely"],
    nextRule: { Daily: 27, Weekly: 27, Monthly: 27, Rarely: 27 },
  },
  {
    questionId: 20,
    category: "Parenting",
    text: "Do you believe in using rewards for good behavior?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { Yes: 28, No: 29 },
  },
  {
    questionId: 21,
    category: "Parenting",
    text: "How do you approach your child's education outside of school?",
    type: "multiple_choice",
    options: ["Tutoring", "Reading books together", "Educational games", "Other"],
    nextRule: { Tutoring: 30, "Reading books together": 30, "Educational games": 30, Other: 30 },
  },
  {
    questionId: 22,
    category: "Parenting",
    text: "What do you think is the most important factor in raising a well-rounded child?",
    type: "multiple_choice",
    options: ["Education", "Love and support", "Independence", "Social skills", "Other"],
    nextRule: { Education: 23, "Love and support": 24, Independence: 25, "Social skills": 26, Other: 27 },
  },
  {
    questionId: 23,
    category: "Parenting",
    text: "Do you discuss your child's future goals with them?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { Yes: 30, No: 30 },
  },
  {
    questionId: 24,
    category: "Parenting",
    text: "How do you foster a strong bond with your child?",
    type: "multiple_choice",
    options: ["Spending quality time", "Helping with homework", "Being emotionally available", "Other"],
    nextRule: { "Spending quality time": 30, "Helping with homework": 30, "Being emotionally available": 30, Other: 30 },
  },
  {
    questionId: 25,
    category: "Parenting",
    text: "How do you manage your child's screen time?",
    type: "multiple_choice",
    options: ["No screen time", "Set time limits", "Unrestricted", "Other"],
    nextRule: { "No screen time": 26, "Set time limits": 26, "Unrestricted": 26, Other: 26 },
  },
  {
    questionId: 26,
    category: "Parenting",
    text: "Do you engage in physical activities with your child?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { Yes: 27, No: 28 },
  },
  {
    questionId: 27,
    category: "Parenting",
    text: "What physical activities do you enjoy doing with your child?",
    type: "multiple_choice",
    options: ["Walking", "Cycling", "Sports", "Other"],
    nextRule: { Walking: 29, Cycling: 29, Sports: 29, Other: 29 },
  },
  {
    questionId: 28,
    category: "Parenting",
    text: "How do you handle stress as a parent?",
    type: "multiple_choice",
    options: ["Exercise", "Meditation", "Talking to others", "Other"],
    nextRule: { Exercise: 30, Meditation: 30, "Talking to others": 30, Other: 30 },
  },
  {
    questionId: 29,
    category: "Parenting",
    text: "Do you make time for self-care?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { Yes: 30, No: 30 },
  },
  {
    questionId: 30,
    category: "Parenting",
    text: "Are you satisfied with your approach to parenting?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { Yes: null, No: null }, // End of the questionnaire
  },
  {
    questionId: 1,
    category: "Family/Couple Counselling",
    text: "How often do you spend quality time with your partner?",
    type: "multiple_choice",
    options: ["Every day", "Once a week", "Once a month", "Rarely"],
    nextRule: { "Every day": 2, "Once a week": 3, "Once a month": 4, "Rarely": 5 },
  },
  {
    questionId: 2,
    category: "Family/Couple Counselling",
    text: "How do you usually communicate with your partner?",
    type: "multiple_choice",
    options: ["Open discussions", "Arguments", "Silence", "Casual conversations"],
    nextRule: { "Open discussions": 6, "Arguments": 7, "Silence": 8, "Casual conversations": 9 },
  },
  {
    questionId: 3,
    category: "Family/Couple Counselling",
    text: "Do you feel emotionally supported by your partner?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 10, "No": 11 },
  },
  {
    questionId: 4,
    category: "Family/Couple Counselling",
    text: "What is the biggest challenge in your relationship?",
    type: "multiple_choice",
    options: ["Communication issues", "Financial stress", "Parenting differences", "Lack of intimacy"],
    nextRule: { "Communication issues": 12, "Financial stress": 13, "Parenting differences": 14, "Lack of intimacy": 15 },
  },
  {
    questionId: 5,
    category: "Family/Couple Counselling",
    text: "Do you and your partner agree on how to manage finances?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 16, "No": 17 },
  },
  {
    questionId: 6,
    category: "Family/Couple Counselling",
    text: "How do you resolve conflicts with your partner?",
    type: "multiple_choice",
    options: ["Calm discussions", "Shouting matches", "Silent treatment", "Avoidance"],
    nextRule: { "Calm discussions": 18, "Shouting matches": 19, "Silent treatment": 20, "Avoidance": 20 },
  },
  {
    questionId: 7,
    category: "Family/Couple Counselling",
    text: "Do you often feel misunderstood by your partner?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 20, "No": 20 },
  },
  {
    questionId: 8,
    category: "Family/Couple Counselling",
    text: "How often do you argue about household chores?",
    type: "multiple_choice",
    options: ["Never", "Occasionally", "Frequently", "Constantly"],
    nextRule: { "Never": 20, "Occasionally": 20, "Frequently": 20, "Constantly": 20 },
  },
  {
    questionId: 9,
    category: "Family/Couple Counselling",
    text: "Are you satisfied with the level of intimacy in your relationship?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 20, "No": 20 },
  },
  {
    questionId: 10,
    category: "Family/Couple Counselling",
    text: "How do you show affection towards your partner?",
    type: "multiple_choice",
    options: ["Physical touch", "Words of affirmation", "Acts of service", "Gifts"],
    nextRule: { "Physical touch": 20, "Words of affirmation": 20, "Acts of service": 20, "Gifts": 20 },
  },
  {
    questionId: 11,
    category: "Family/Couple Counselling",
    text: "Do you and your partner have a shared vision for the future?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 12, "No": 13 },
  },
  {
    questionId: 12,
    category: "Family/Couple Counselling",
    text: "Do you feel that your partner listens to you?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 14, "No": 15 },
  },
  {
    questionId: 13,
    category: "Family/Couple Counselling",
    text: "How often do you go on dates with your partner?",
    type: "multiple_choice",
    options: ["Once a week", "Once a month", "Every few months", "Never"],
    nextRule: { "Once a week": 16, "Once a month": 17, "Every few months": 18, "Never": 19 },
  },
  {
    questionId: 14,
    category: "Family/Couple Counselling",
    text: "Are you satisfied with the amount of personal space you get in your relationship?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 20, "No": 20 },
  },
  {
    questionId: 15,
    category: "Family/Couple Counselling",
    text: "How do you handle stress in your relationship?",
    type: "multiple_choice",
    options: ["Talk it out", "Ignore it", "Fight about it", "Seek external help"],
    nextRule: { "Talk it out": 20, "Ignore it": 20, "Fight about it": 20, "Seek external help": 20 },
  },
  {
    questionId: 16,
    category: "Family/Couple Counselling",
    text: "Do you feel appreciated by your partner?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 20, "No": 20 },
  },
  {
    questionId: 17,
    category: "Family/Couple Counselling",
    text: "How often do you talk about the future of your relationship?",
    type: "multiple_choice",
    options: ["Often", "Occasionally", "Rarely", "Never"],
    nextRule: { "Often": 20, "Occasionally": 20, "Rarely": 20, "Never": 20 },
  },
  {
    questionId: 18,
    category: "Family/Couple Counselling",
    text: "Do you both make decisions together or separately?",
    type: "multiple_choice",
    options: ["Together", "Separately", "It varies", "Not sure"],
    nextRule: { "Together": 20, "Separately": 20, "It varies": 20, "Not sure": 20 },
  },
  {
    questionId: 19,
    category: "Family/Couple Counselling",
    text: "Do you trust your partner completely?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 20, "No": 20 },
  },
  {
    questionId: 20,
    category: "Family/Couple Counselling",
    text: "Do you think your relationship has room for improvement?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": null, "No": null },
  },
  {
    questionId: 1,
    category: "Children/Teen/Students Counselling",
    text: "How often do you feel stressed about school or academics?",
    type: "multiple_choice",
    options: ["Daily", "A few times a week", "Occasionally", "Never"],
    nextRule: { "Daily": 2, "A few times a week": 3, "Occasionally": 4, "Never": 5 },
  },
  {
    questionId: 2,
    category: "Children/Teen/Students Counselling",
    text: "Do you feel that your workload at school is manageable?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 6, "No": 7 },
  },
  {
    questionId: 3,
    category: "Children/Teen/Students Counselling",
    text: "How often do you feel overwhelmed by your assignments and homework?",
    type: "multiple_choice",
    options: ["Daily", "A few times a week", "Occasionally", "Never"],
    nextRule: { "Daily": 8, "A few times a week": 9, "Occasionally": 10, "Never": 11 },
  },
  {
    questionId: 4,
    category: "Children/Teen/Students Counselling",
    text: "Do you have someone to talk to when you're feeling stressed or anxious?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 12, "No": 13 },
  },
  {
    questionId: 5,
    category: "Children/Teen/Students Counselling",
    text: "Do you find it difficult to balance school and personal life?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 14, "No": 15 },
  },
  {
    questionId: 6,
    category: "Children/Teen/Students Counselling",
    text: "Do you feel supported by your teachers or school staff?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 16, "No": 17 },
  },
  {
    questionId: 7,
    category: "Children/Teen/Students Counselling",
    text: "Do you feel confident about your academic abilities?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 18, "No": 19 },
  },
  {
    questionId: 8,
    category: "Children/Teen/Students Counselling",
    text: "Do you struggle with maintaining good grades or completing assignments on time?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 20, "No": 20 },
  },
  {
    questionId: 9,
    category: "Children/Teen/Students Counselling",
    text: "How often do you feel worried about your future or career choices?",
    type: "multiple_choice",
    options: ["Daily", "A few times a week", "Occasionally", "Never"],
    nextRule: { "Daily": 20, "A few times a week": 20, "Occasionally": 20, "Never": 20 },
  },
  {
    questionId: 10,
    category: "Children/Teen/Students Counselling",
    text: "Do you feel pressure from your parents or guardians to succeed academically?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 20, "No": 20 },
  },
  {
    questionId: 11,
    category: "Children/Teen/Students Counselling",
    text: "Do you find it easy to ask for help when you need it?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 20, "No": 20 },
  },
  {
    questionId: 12,
    category: "Children/Teen/Students Counselling",
    text: "How often do you feel sad or depressed?",
    type: "multiple_choice",
    options: ["Daily", "A few times a week", "Occasionally", "Never"],
    nextRule: { "Daily": 20, "A few times a week": 20, "Occasionally": 20, "Never": 20 },
  },
  {
    questionId: 13,
    category: "Children/Teen/Students Counselling",
    text: "Do you ever feel isolated or alone in school?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 20, "No": 20 },
  },
  {
    questionId: 14,
    category: "Children/Teen/Students Counselling",
    text: "Do you have any strategies to manage stress at school?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 20, "No": 20 },
  },
  {
    questionId: 15,
    category: "Children/Teen/Students Counselling",
    text: "Are you satisfied with the amount of support you get at school?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 20, "No": 20 },
  },
  {
    questionId: 16,
    category: "Children/Teen/Students Counselling",
    text: "Do you feel like your school environment is conducive to learning?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 20, "No": 20 },
  },
  {
    questionId: 17,
    category: "Children/Teen/Students Counselling",
    text: "Do you experience any bullying or teasing at school?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 20, "No": 20 },
  },
  {
    questionId: 18,
    category: "Children/Teen/Students Counselling",
    text: "Do you find it difficult to stay motivated to complete your schoolwork?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": 20, "No": 20 },
  },
  {
    questionId: 19,
    category: "Children/Teen/Students Counselling",
    text: "How often do you feel that you don't fit in or belong at school?",
    type: "multiple_choice",
    options: ["Daily", "A few times a week", "Occasionally", "Never"],
    nextRule: { "Daily": 20, "A few times a week": 20, "Occasionally": 20, "Never": 20 },
  },
  {
    questionId: 20,
    category: "Children/Teen/Students Counselling",
    text: "Would you like help with managing school-related stress or anxiety?",
    type: "yesno",
    options: ["Yes", "No"],
    nextRule: { "Yes": null, "No": null },
  }
]
const clearAndAddQuestions = async (category) => {
  try {
    // Connect to MongoDB using your connection string from .env
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB");

    // Clear all questions in the specified category
    const deleteResult = await Question.deleteMany({ category });
    console.log(`${deleteResult.deletedCount} existing questions cleared for category: ${category}`);

    // Insert the new questions for the specified category
    const questionsToInsert = questions.filter((q) => q.category === category);

    if (questionsToInsert.length > 0) {
      const inserted = await Question.insertMany(questionsToInsert);
      console.log(`${inserted.length} questions seeded for "${category}" category.`);
    } else {
      console.log(`No questions found to insert for category "${category}".`);
    }

    await mongoose.connection.close();
  } catch (error) {
    console.error("Error clearing and adding questions:", error);
    await mongoose.connection.close();
  }
};

// Run the function for the category you want to clear and add questions
clearAndAddQuestions("Parenting");  // Change "Parenting" to the category you want
